---

# Don't modify this file, use local.config.yml instead. Place values
# you want to override there.

# Springboard can't run Ubuntu 1604 because of a db schema bug.
vagrant_box: geerlingguy/ubuntu1404
vagrant_hostname: sbvm.local
vagrant_machine_name: sbvm
vagrant_ip: 0.0.0.0

vagrant_synced_folders:
  - local_path:  .
    destination: /var/www/springboard
    type: nfs
    create: true

# Stop drupalvm from doing anything to install Drupal so SpringboardVM can handle it.
build_makefile: false
drupal_build_makefile: false
build_composer: false
drupal_composer_path: false
build_composer_project: false
drupal_build_composer: false
drupal_build_composer_project: false
drupal_composer_dependencies: []
install_site: false
drupal_install_site: false

# Don't change this block. Really.
sbvm_site_dir: "/var/www/springboard/sites"
drupal_composer_install_dir: "/var/www/springboard/sites" #deprecated
drupal_core_dir: "sb_default/web"
drupal_testing_dir: "sb_testing/web"
drupal_core_project_dir: "sb_default"
drupal_testing_project_dir: "sb_testing"
drupal_core_path: "{{ sbvm_site_dir }}/{{drupal_core_dir}}"
drupal_testing_path: "{{ sbvm_site_dir }}/{{drupal_testing_dir}}"
drupal_domain: "{{ vagrant_machine_name }}.local"
drupal_testing_domain: "{{ vagrant_machine_name }}-test.local"
#drush_path: '/usr/local/bin/drush'

# Cron jobs are added to the vagrant user's crontab. Keys include name
# (required), minute, hour, day, weekday, month, job (required), and state.
drupalvm_cron_jobs: []

installed_extras:
  - adminer
  # - blackfire
  # - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - upload-progress
  - varnish
  - xdebug
  - xhprof

# Add any extra apt or yum packages you would like installed.
drush_version: "8.1.10"

php_version: "5.6"
php_install_recommends: no
extra_packages:
  - php5.6
  - php5.6-apcu
  - php5.6-mcrypt
  - php5.6-cli
  - php5.6-common
  - php5.6-curl
  - php5.6-dev
  - php5.6-fpm
  - php5.6-gd
  - php5.6-sqlite3
  - php5.6-xml
  - php5.6-mbstring
  - php5.6-soap
  - php-pear
  - libpcre3-dev
  - libapache2-mod-php5.6
php_conf_paths:
  - /etc/php/5.6/fpm
  - /etc/php/5.6/apache2
  - /etc/php/5.6/cli
php_extension_conf_paths:
  - /etc/php/5.6/fpm/conf.d
  - /etc/php/5.6/apache2/conf.d
  - /etc/php/5.6/cli/conf.d
php_fpm_daemon: php5.6-fpm
php_fpm_conf_path: "/etc/php/5.6/fpm"
php_fpm_pool_conf_path: "/etc/php/5.6/fpm/pool.d/www.conf"
php_mysql_package: php5.6-mysql

# If you install `redis`:
php_redis_package: php5.6-redis

# If you install `memcached`:
php_memcached_package: php5.6-memcached

# If you install `xhprof`:
xhprof_download_url: https://github.com/phacility/xhprof/archive/master.tar.gz
xhprof_download_folder_name: xhprof-master

php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/opt/mailhog/mhsendmail"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

# Run specified scripts before or after VM is provisioned. Path is relative to
# the `provisioning/playbook.yml` file.
pre_provision_scripts:
 - "../../../../scripts/pre-provision.sh"
springboard_vm_pre_provision_scripts:
 - "../scripts/pre-provision.sh"

# One script, two relative paths, depdending on context
post_provision_scripts:
 - "../../../../scripts/post-provision.sh"
springboard_vm_post_provision_scripts:
 - "../scripts/post-provision.sh"


springboard_vm_vm_path: "../vendor/geerlingguy/drupal-vm/provisioning"
springboard_vm_vm_roles_path: "../vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy"
post_provision_tasks_dir: "../../../../config/drush-aliases.yml"
springboard_vm_post_provision_tasks_dir: "../config/drush-aliases.yml"
springboard_vm_apache_vhosts_template: "../vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.apache/templates/vhosts.conf.j2"

# A unique SpringboardVM prefix for drush aliases, to keep them from
# getting mismatched with aliases from other dev environments.
springboard_vm_drush_alias_uniqifier: ''


# MySQL Configuration.
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php

# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 1
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256

known_hosts_path: ~/.ssh/known_hosts
ssh_home: "{{ sbvm_site_dir }}"

apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load
  - mime.load


apache_vhosts:

# Testing Site
  - servername: "{{ drupal_testing_domain }}"
    serveralias: "www.{{ drupal_testing_domain }}"
    documentroot: "{{ drupal_testing_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# Default DrupalVM virtual hosts.

  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

apache_vhosts_ssl:
  - servername: "{{ drupal_testing_domain }}"
    documentroot: "{{ drupal_testing_path }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# Default DrupalVM virtual hosts.
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    documentroot: "{{ dashboard_install_dir }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# create additional databases. Use the docroot name for the database name.
# If you don't specify one here, drush will create it during post-provision.
mysql_databases:
# Testing site
  - name: "{{ drupal_testing_project_dir }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

# Default DrupalVM Db.
  - name: "{{ drupal_core_project_dir }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "*.*:ALL"

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9200"
  - "3306"