---
# Tries to run the minimum necessary tasks to re-provision the apache vhost definitions
# and create databases for new hosts.




- hosts: all
  become: yes
  vars_files:
    - ../vendor/geerlingguy/drupal-vm/default.config.yml
    - config.yml
    - local.config.yml
    - "{{ druvmoser_vm_path }}/vars/main.yml"
    - "{{ druvmoser_vm_path }}/vars/Debian.yml"
    - "{{ druvmoser_vm_path }}/vars/RedHat.yml"

  # Even though we're only updating vhosts, we may need to include all roles.
  roles:
    - { role: "{{ druvmoser_vm_roles_path }}.apache", when: drupalvm_webserver == 'apache' }
    - { role: "{{ druvmoser_vm_roles_path }}.apache-php-fpm", when: drupalvm_webserver == 'apache' }
    - role: "{{ druvmoser_vm_roles_path }}.php-xhprof"
      workspace: "/root/php{{ php_version }}"
      when: '"xhprof" in installed_extras'
    - role: "{{ druvmoser_vm_roles_path }}.php-xdebug"
      workspace: "/root/php{{ php_version }}"
      when: '"xdebug" in installed_extras'
    - role: "{{ druvmoser_vm_path }}/roles/thom8.php-upload-progress"
      workspace: "/root/php{{ php_version }}"
      when: '"upload-progress" in installed_extras'
    - { role: "{{ druvmoser_vm_roles_path }}.blackfire", when: '"blackfire" in installed_extras' }
    - { role: "{{ druvmoser_vm_roles_path }}.adminer", when: '"adminer" in installed_extras' }
    - { role: "{{ druvmoser_vm_roles_path }}.pimpmylog", when: '"pimpmylog" in installed_extras' }
    - { role: "{{ druvmoser_vm_roles_path }}.daemonize", when: '"mailhog" in installed_extras' }
    - { role: "{{ druvmoser_vm_roles_path }}.mailhog", when: '"mailhog" in installed_extras' }
    - { role: "{{ druvmoser_vm_roles_path }}.mysql", when: drupalvm_database == 'mysql' }
    - { role: "{{ druvmoser_vm_roles_path }}.php-mysql", when: drupalvm_database == 'mysql' }
    - { role: "{{ druvmoser_vm_roles_path }}.drupal-console", when: 'drupal_major_version > 7 and "drupalconsole" in installed_extras' }
    - { role: "{{ druvmoser_vm_roles_path }}.drush", when: '"drush" in installed_extras' }
    - { role: "{{ druvmoser_vm_roles_path }}.memcached", when: '"memcached" in installed_extras' }
    - { role: "{{ druvmoser_vm_roles_path }}.php-memcached", when: '"memcached" in installed_extras' }
    - { role: "{{ druvmoser_vm_path }}/roles/franklinkim.newrelic", when: '"newrelic" in installed_extras' }
    - { role: "{{ druvmoser_vm_path }}/roles/arknoll.selenium", when: '"selenium" in installed_extras' }
    - role: "{{ druvmoser_vm_roles_path }}.java"
      when: >
        "java" in installed_extras or
        "solr" in installed_extras or
        "selenium" in installed_extras or
        "elasticsearch" in installed_extras


  # These tasks are lifted from the apache role.
  tasks:

    - name: DruVMoser baby.
      set_fact:
        druvmoser_shim: "This is just a placeholder for the 'start-at-task' ansible flag"

    # Include variables and define needed variables.
    - name: Include OS-specific variables.
      include_vars: "{{ druvmoser_vm_roles_path }}.apache/vars/{{ ansible_os_family }}.yml"

    - name: Define apache_packages.
      set_fact:
        apache_packages: "{{ __apache_packages | list }}"
      when: apache_packages is not defined

    # Figure out what version of Apache is installed.
    - name: Get installed version of Apache.
      shell: "{{ apache_daemon_path }}{{ apache_daemon }} -v"
      changed_when: false
      always_run: yes
      register: _apache_version

    - name: Create apache_version variable.
      set_fact:
        apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"

    - include_vars: "{{ druvmoser_vm_roles_path }}.apache/vars/apache-22.yml"
      when: "apache_version.split('.')[1] == '2'"

    - include_vars: "{{ druvmoser_vm_roles_path }}.apache/vars/apache-24.yml"
      when: "apache_version.split('.')[1] == '4'"

    - name: Add apache vhosts configuration.
      template:
        src: "{{ druvmoser_vm_roles_path }}.apache/templates/vhosts.conf.j2"
        dest: "/etc/apache2/sites-available/vhosts.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart apache
      when: apache_create_vhosts

    - name: Add vhost symlink in sites-enabled.
      file:
        src: "/etc/apache2/sites-available/vhosts.conf"
        dest: "/etc/apache2/sites-enabled/vhosts.conf"
        state: link
      notify: restart apache
      when: apache_create_vhosts

    - name: Run configured pre-provision shell scripts.
      script: "{{ item }}"
      with_items: "{{ druvmoser_pre_provision_scripts|default([]) }}"

    - name: Run configured post-provision shell scripts.
      script: "{{ item }}"
      with_items: "{{ druvmoser_post_provision_scripts|default([]) }}"

    - name: Run configured post-provision ansible task files.
      include: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob:
        - "{{ druvmoser_post_provision_tasks_dir|default(omit) }}"

    - name: Copy dashboard page into place.
      template:
        src: ../templates/dashboard.html.j2
        dest: "{{ dashboard_install_dir }}/index.html"
        mode: 0644
