---

# Makes site aliases using the document root folder name for the sake of brevity.

- name: Check if local Drush configuration folder exists.
  stat:
    path: ~/.drush
  register: local_drush_config_folder
  delegate_to: 127.0.0.1
  become: no
  when: configure_drush_aliases

- name: Create Drush configuration folder if it doesn't exist.
  file:
    path: ~/.drush
    state: directory
  delegate_to: 127.0.0.1
  become: no
  when: configure_drush_aliases and (local_drush_config_folder.stat.exists == false)

# Note that this doesn't work for Windows, since Ansible's running in the VM.
- name: Configure host machine drush aliases.
  template: src={{ item }} dest="~/.drush/{{ vagrant_machine_name }}-short.aliases.drushrc.php"
  with_first_found:
    - files:
       - ../../../../templates/local.aliases.drushrc.php.j2
       - ../templates/local.aliases.drushrc.php.j2
  delegate_to: 127.0.0.1
  become: no
  when:
   - configure_drush_aliases