
# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance. Otherwise, leave this alone.
#vagrant_hostname: sbvm.dev
#vagrant_machine_name: sbvm
#vagrant_ip: 0.0.0.0
# springboard_vm_drush_alias_uniqifier: 'dd'

# Add additional Springboard installs and vhosts.
# Don't use any special characters in the docroot name. Only a-z are allowed.

apache_vhosts:

# A Custom Site
# Keep your project root names short. They become drush aliases.
# Projectroot and document root are both required. Document root
# should always be projectroot + '/web'. Other conifgurations will not
# work.
  - servername: "another-site.dev"
    serveralias: "www.another-site.dev"
    projectroot: "{{sbvm_site_dir}}/ano"
    #sustainer key = project root + "_sustainer_key"
    ano_sustainer_key: "another-site.dev"
    documentroot: "{{sbvm_site_dir}}/ano/web" #must be /web
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# Don't forget to define the apache_vhosts_ssl entry below, as well.

# You need to maintain the default DrupalVM vhost definitions
# in this file too. Don't change these unless you are running multiple
# springboard_vm installs.

# The Default Testing Site
  - servername: "{{ drupal_testing_domain }}"
    serveralias: "www.{{ drupal_testing_domain }}"
    documentroot: "{{ drupal_testing_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# Default  virtual hosts.

  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

apache_vhosts_ssl:

  # your cusotm site ssl entry
  - servername: "another-site.dev"
    documentroot: "{{sbvm_site_dir}}/ano/web"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  # Default SpringboardVM virtual hosts.
  - servername: "{{ drupal_testing_domain }}"
    documentroot: "{{ drupal_testing_path }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    documentroot: "{{ dashboard_install_dir }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"