# Add additional Springboard installs and vhosts.

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
#vagrant_hostname: springboardvm.dev
#vagrant_machine_name: springboardvm
#vagrant_ip: 0.0.0.0

# You're going to want to use the "sites" directory to hold them: ex, "sites/mynewdocroot"
# Don't use any special characters in the docroot name. Only a-z and "/" are allowed.

# If you're adding a new site to a previously provisioned SpringboardVM, then you need to:
# run `composer update`
# run `vagrant provision`

apache_vhosts:
#custom virtual host
  - servername: "test2.dev"
    serveralias: "www.test2.dev"
    documentroot: "{{drupal_composer_install_dir}}/test2"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/{{drupal_composer_install_dir}}/test2"

# Default DrupalVM virtual hosts.

  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ adminer_install_dir }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ php_xhprof_html_dir }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ pimpmylog_install_dir }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ dashboard_install_dir }}"
          DirectoryIndex index.html

apache_vhosts_ssl:
  - servername: "test2.dev"
    documentroot: "{{drupal_composer_install_dir}}/test2"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/test2"

# Default DrupalVM virtual hosts.

  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"


# create additional databases.
mysql_databases:
  - name:  "tickets"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: "{{ drupal_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "*.*:ALL"

# Allow connections from any IP. Useful for acceptance tests.
#mysql_bind_address: 0.0.0.0