# Items defined in this file will completely override items defined in
# the other yaml files. So you have to redefine the entire vhosts array
# instead of just adding new items to it. This is a limitation of the DrupalVM
# ansible playbook.

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance. Otherwise, leave this alone.
#vagrant_hostname: druvmoser.dev
#vagrant_machine_name: druvmoser
#vagrant_ip: 0.0.0.0


# Add additional Springboard installs and vhosts.
# Don't use any special characters in the docroot name. Only a-z are allowed.

# If you're adding a new site to a previously provisioned SpringboardVM, then you need to:
# run `composer update`
# run `vagrant provision`

apache_vhosts:

# A Custom Site
  - servername: "another-site.dev"
    serveralias: "www.another-site.dev"
    documentroot: "{{drupal_composer_install_dir}}/another_site"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# You need to maintain the default DrupalVM vhost definitions
# in this file too. Don't change these unless you are running multiple
# druvmoser installs.

# The Default Testing Site
  - servername: "{{ drupal_testing_domain }}"
    serveralias: "www.{{ drupal_testing_domain }}"
    documentroot: "{{ drupal_testing_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# Default  virtual hosts.

  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

apache_vhosts_ssl:

  - servername: "another-site.dev"
    documentroot: "{{drupal_composer_install_dir}}/another_site"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ drupal_testing_domain }}"
    documentroot: "{{ drupal_testing_path }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# Default DrupalVM virtual hosts.
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"


# create additional databases. Use the docroot name for the database name.
# If you don't specify one here, drush will create it during post-provision.
mysql_databases:
# Testing site
  - name: "{{ drupal_testing_dir }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

# Default DrupalVM Db.
  - name: "{{ drupal_core_dir }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "*.*:ALL"

# Allow connections from any IP. Useful for acceptance tests.
#mysql_bind_address: 0.0.0.0